// DAW Export Templates
export class DAWTemplates {
  constructor() {
    this.templates = {
      logic: {
        name: 'Logic Pro X',
        trackPrefix: '',
        trackSuffix: '',
        channelMapping: {
          melody: { channel: 0, program: 0, name: 'Lead Melody' },
          chords: { channel: 1, program: 0, name: 'Harmony' },
          bass: { channel: 2, program: 33, name: 'Bass/808' },
          drums: { channel: 9, program: 0, name: 'Drums' }
        },
        copyright: 'Generated by Prompt2MIDI Studio Pro'
      },
      fl: {
        name: 'FL Studio',
        trackPrefix: '',
        trackSuffix: '',
        channelMapping: {
          melody: { channel: 0, program: 81, name: 'Melody' },
          chords: { channel: 1, program: 0, name: 'Chords' },
          bass: { channel: 2, program: 38, name: 'Bass' },
          drums: { channel: 9, program: 0, name: 'Drums' }
        },
        copyright: 'Generated by Prompt2MIDI Studio Pro'
      },
      ableton: {
        name: 'Ableton Live',
        trackPrefix: '',
        trackSuffix: ' Track',
        channelMapping: {
          melody: { channel: 0, program: 0, name: 'Melody' },
          chords: { channel: 1, program: 0, name: 'Chords' },
          bass: { channel: 2, program: 33, name: 'Bass' },
          drums: { channel: 9, program: 0, name: 'Drums' }
        },
        copyright: 'Generated by Prompt2MIDI Studio Pro'
      },
      generic: {
        name: 'Generic/Standard',
        trackPrefix: '',
        trackSuffix: '',
        channelMapping: {
          melody: { channel: 0, program: 0, name: 'Melody' },
          chords: { channel: 1, program: 0, name: 'Chords' },
          bass: { channel: 2, program: 32, name: 'Bass' },
          drums: { channel: 9, program: 0, name: 'Drums' }
        },
        copyright: 'Generated by Prompt2MIDI Studio Pro'
      }
    };
  }

  applyTemplate(tracks, templateId = 'generic') {
    const template = this.templates[templateId] || this.templates.generic;
    
    return tracks.map(track => {
      const mapping = template.channelMapping[track.type];
      if (!mapping) return track;
      
      return {
        ...track,
        name: template.trackPrefix + mapping.name + template.trackSuffix,
        channel: mapping.channel,
        program: mapping.program
      };
    });
  }

  getTemplate(templateId) {
    return this.templates[templateId] || this.templates.generic;
  }
}